//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2502
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

unit astar3d_point3d;

interface
uses sysutils,classes, VectorGeometry, VectorTypes, core_utils;
type

  { TPoint3D }

  TPoint3D = Tvector3i;

  function GetDistanceSquared(p1,p2: TPoint3D): Integer;
  function EqualsSS(p1,p2: TPoint3D): Boolean;
  //function GetHashCode: Integer; override;
  //function ToString: string; override;
  //function vector3i: TVector3i;
  //function vector3f: TVector3f;

  //function Zero:TPoint3D;


implementation

function GetDistanceSquared(p1, p2: TPoint3D): Integer;
var
  dz: Integer;
  dy: Integer;
  dx: Integer;
begin
  dx := (p1[0] - p2[0]);
  dy := (p1[1] - p2[1]);
  dz := (p1[2] - p2[2]);
  Result := (dx * dx) + (dy * dy) + (dz * dz);
end;

function EqualsSS(p1, p2: TPoint3D): Boolean;
begin
  Result := (((p1[0] = p2[0]) and (p1[2] = p2[2])) and (p1[1] = p2[1]));
end;



end.

